---
title: "Resources"
description: |
  Links to resources of interest to R-Govys members 
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Training materials for R
<details>
  <summary>Click to expand!</summary>
  
  There are many many online R resources. These are some that NMFS R users have found particular helpful or R courses that were developed by NMFS or other federal agencies.
  
* [R Consortium YouTube Channel](https://www.youtube.com/channel/UC_R5smHVXRYGhZYDJsnXTwg) many lectures on R topics.
* [HappyGitwR](https://happygitwithr.com/)
* [GAMS in R](https://noamross.github.io/gams-in-r-course)
* [Data Visualizations, mostly in R](https://github.com/USGS-VIZLAB) USGS GitHub org that has many examples of data visualizations.
* [Lots of environmental data examples in R](http://eco-data-science.github.io/) Click on "PREVIOUS SESSIONS" to go to tutorials.
* [USGS R Training courses](https://owi.usgs.gov/R/training-curriculum/intro-curriculum/)
* [West Coast Region R course](https://chanteddavis-noaa.github.io/WCR_RStarterPack/about.html)
</details>

## Training materials for Python
<details>
  <summary>Click to expand!</summary>
  
* [Visualations and Dashboards in Python](https://towardsdatascience.com/visualization-and-interactive-dashboard-in-python-c2f2a88b2ba3 )
</details>
* [NASA EarthData webinars](https://earthdata.nasa.gov/learn/user-resources/webinars-and-tutorials) Many of these are Python examples and include links to the repos.

## NOAA specific packages
<details>
  <summary>Click to expand!</summary>
  
* [rnoaa](https://docs.ropensci.org/rnoaa/) An R interface to many NOAA data sources: climate data, ocean data, weather data, etc.
* [crawl](https://jmlondon.github.io/crwexampleakbs/analysis.html) An R package that provides analytical tools for estimating the movement paths of animals from telemetry data.
* [uswebr](https://github.com/jmlondon/uswebr) RMarkdown template based on the U.S. Web Design Standards. [Example of output](https://jmlondon.github.io/crwexampleakbs/analysis.html).
</details>

## Recommended general packages
<details>
  <summary>Click to expand!</summary>

<br/>

* [{tidyverse}](https://www.tidyverse.org/)
* [{ggplot2}](https://ggplot2.tidyverse.org/)
* [{styler}](https://styler.r-lib.org/) Style your code using the styler add-in for RStudio
* [{distill}](https://rstudio.github.io/distill/) Distill for R Markdown is a web publishing format optimized for scientific and technical communication. Distill articles include: math, citations, footnotes, multiple ways to output content (website, blog, article).
</details>



## Other Open Science Efforts in Government

* **GitHub in the US federal agencies** GitHub is widely used by US federal agencies and scientists to deliver products and collaborate. This [wiki](https://github.com/Openscapes/2021-noaa-nmfs/wiki/1-GitHub-in-gov) links to some of those efforts.
* [**NASA EarthData**](https://earthdata.nasa.gov/)
* [**USGS R**](https://owi.usgs.gov/R/)


